[settings]
# pages are the top level menu choices only. Not to be confused with the generated code from_source
pages = "\
    entities|separator|\
    monitors|separator|\
    names|separator|\
    digests|explorer|separator|\
    settings|support|\
    accounts|summary|tags|signatures|caches|other"

schemas = "\
    entities|monitors|accounts|summary|tags|\
    names|signatures|digests|\
    caches|other|settings|settings-schemas|settings-systems|support|\
    explorer|\
    explorer-blocks|explorer-transactions|explorer-receipts|explorer-logs|\
    explorer-traces|explorer-traceActions|explorer-traceResults|\
    explorer-functions|explorer-parameters|explorer-abis|\
    explorer-pricequotes|explorer-pricesources"

from_source = "\
    entities|monitors|accounts|summary|tags|\
    explorer-blocks|explorer-transactions|explorer-receipts|explorer-logs|explorer-traces|\
    names|signatures|caches|other"
