[settings]
class = "CEntities"
recordIcons =  "editing,view,exporting"
defaultSort = "tags,name,client"
cmdUrl = "names"
dataUrl = "names"
dataQuery = "entities"
imports = "||getServerData, sendServerCommand, sortArray, sortStrings, handleClick, replaceRecord, stateFromStorage|||"

[[subpages]]
list = [
    { page = "entities", subpage = "" },
]
