[settings]
class = "CMonitors"
recordIcons = "viewing,editing,view,exporting,importing"
defaultSort = "tags,address"
defaultSearch = "tags,address,name"
dataUrl = "status"
dataQuery = "modes=monitors&details"
cmdUrl = "rm"
imports = "||getServerData, sendServerCommand, sortArray, sortStrings, handleClick, navigate, replaceRecord, stateFromStorage|||"

[[subpages]]
list = [
    { page = "monitors", subpage = "" },
]
